config/routes.rb
Rails.application.routes.draw do
  
  get 'bridge/index'
  resources :themes
  resources :sitemap, :only => :index
  get 'sitemap.xml', :controller => "sitemap", :action => "xml"

  resources :scategories
  resources :picks
  resources :featureds
  # root 'posts#index'
  root 'picks#index'


  resources :sales
  devise_for :users
  resources :posts

  get '/sales/hashtag/:name', to:'sales#hashtags'
  get '/featureds/fhashtag/:name', to:'featureds#hashtags'
  get '/picks/phashtag/:name', to:'picks#hashtags'


  #Bridge Page
  get '/bridge/manage_hashtags'
  get '/bridge/top_100'
  get '/bridge/half_deal'
  get '/bridge/under_deal'
  get '/bridge/sales'
  get '/bridge/delete_old_deal'
  get '/bridge/search'
  get '/bridge/about_us'
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/theme.rb
class Theme < ApplicationRecord
  has_and_belongs_to_many :tags
  belongs_to :user
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  # GET /themes
  # GET /themes.json
  def index
    @pagy, @themes = pagy(Theme.all.order("created_at DESC"), items: 30)
  end

  # GET /themes/1
  # GET /themes/1.json
  def show
  end

  # GET /themes/new
  def new
    @theme = Theme.new
  end

  # GET /themes/1/edit
  def edit
  end

  # POST /themes
  # POST /themes.json
  def create
    @theme = Theme.new(theme_params)
    @theme.user = current_user
    respond_to do |format|
      if @theme.save
        format.html { redirect_to "/themes", notice: 'Theme was successfully created.' }
        format.json { render :show, status: :created, location: @theme }
      else
        format.html { render :new }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /themes/1
  # PATCH/PUT /themes/1.json
  def update
    respond_to do |format|
      if @theme.update(theme_params)
        format.html { redirect_to "/themes", notice: 'Theme was successfully updated.' }
        format.json { render :show, status: :ok, location: @theme }
      else
        format.html { render :edit }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /themes/1
  # DELETE /themes/1.json
  def destroy
    @theme.destroy
    respond_to do |format|
      format.html { redirect_to themes_url, notice: 'Theme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theme
      @theme = Theme.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def theme_params
      params.require(:theme).permit(:t_title, :t_image, :t_link, :t_hashtag, :t_source, :t_description)
    end
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/themes/_form.html.erb
<div class="hotdeal_form">
  <%= simple_form_for(@theme) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="basic_info">
      <%= f.input :t_image, label: "썸네일" %>
      <%= f.input :t_title, label: "제목" %>
      <%= f.input :t_description, label: "설명" %>
      <%= f.input :t_link, label: "세일해시태그 주소[]" %>
      <%= f.input :t_hashtag, label: "Theme 해시태그"  %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/themes/edit.html.erb
<% if current_user && current_user.admin %>
  <div class="wrap">
    <h1>Editing Theme</h1>
    <%= render 'form', theme: @theme %>
    <%= link_to 'Show', @theme %> |
    <%= link_to 'Back', themes_path %>
  </div>
<% end %>

app/views/themes/index.html.erb
<%= render 'shared/header' %>

<div class="index-wrap blog-wrap">
  <div class="wrap">

    <div class="visual clearfix">
      <p>주제별로 찾는 핫딜 가이드</p>
      <h2>HotDeals Guide</h2>
    </div>

    <% if current_user && current_user.admin %>
      <div class="index-amdin">
        <%= link_to 'New Theme', new_theme_path %>
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
      </div>
    <% end %>

   <!--  <div class="theme-box clearfix">
      <% @themes.each do |theme| %>
        <a href="/sales/hashtag/<%= theme.t_link %>">
          <div class="card">
            <img src="<%= theme.t_image %>" alt="<%= theme.t_title %>" text="<%= theme.t_title %>">
            <div class="inner">
              <h2><%= theme.t_title %></h2>
              <p><%= theme.t_description %></p>
              <h4>by <%= theme.t_source %></h4>
              <% if current_user && current_user.admin %>
                <%= link_to 'Edit', edit_theme_path(theme) %>
                <%= link_to 'Destroy', theme, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            </div>
          </div>
        </a>
      <% end %>
    </div> -->

    <div class="blog-container clearfix">
      <% @themes.each do |theme| %>
        <div class="card">
          <div class="card-header">
              <a class="to_tag" href="/sales/hashtag/<%= theme.t_link %>"><img class="theme_img" src="<%= theme.t_image %>" alt="<%= theme.t_title %>" text="<%= theme.t_title %>"></a>
          </div>
          <div class="card-body">
            <% if current_user && current_user.admin %>
              <span>
                  <%= link_to 'Edit', edit_theme_path(theme) %>
                  <%= link_to 'Destroy', theme, method: :delete, data: { confirm: 'Are you sure?' } %>            
              </span>
            <% end %>
            <a class="to_tag" href="/sales/hashtag/<%= theme.t_link %>"><h4><%= theme.t_title %></h4></a>
            <!-- <p><%= theme.t_description %></p> -->
            <div class="card-user">
                <img src="<%=asset_path 'ave71.png' %>" alt="Avenue71">
                <div class="user-info">
                    <h5 >Editor</h5>
                    <small >Avenue71</small>
                </div>
            </div>
          </div>
        </div>
      <% end %>   
    </div>
    <%= raw pagy_nav(@pagy) %>

  </div>
</div>

app/views/themes/new.html.erb
<% if current_user && current_user.admin %>
  <div class="wrap">
    <h1>New Theme</h1>
    <%= render 'form', theme: @theme %>
    <%= link_to 'Back', themes_path %>
  </div>
<% end %>

app/views/themes/show.html.erb
<%= link_to 'Edit', edit_theme_path(@theme) %> |
<%= link_to 'Back', themes_path %>