config/routes.rb
Rails.application.routes.draw do
  
  get 'bridge/index'
  resources :themes
  resources :sitemap, :only => :index
  get 'sitemap.xml', :controller => "sitemap", :action => "xml"

  resources :scategories
  resources :picks
  resources :featureds
  # root 'posts#index'
  root 'picks#index'


  resources :sales
  devise_for :users
  resources :posts

  get '/sales/hashtag/:name', to:'sales#hashtags'
  get '/featureds/fhashtag/:name', to:'featureds#hashtags'
  get '/picks/phashtag/:name', to:'picks#hashtags'


  #Bridge Page
  get '/bridge/manage_hashtags'
  get '/bridge/top_100'
  get '/bridge/half_deal'
  get '/bridge/under_deal'
  get '/bridge/sales'
  get '/bridge/delete_old_deal'
  get '/bridge/search'
  get '/bridge/about_us'
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/pick.rb
class Pick < ApplicationRecord
  has_and_belongs_to_many :tags
  belongs_to :user

  after_create do
    pick = Pick.find_by(id: self.id)
    phashtags = self.p_hashtag.scan(/[#＃][a-z|A-Z|가-힣|0-9|\w]+/)
    phashtags.uniq.map do |hashtag|
        tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
        pick.tags << tag
    end
  end
  
  before_update do
    pick = Pick.find_by(id: self.id)
    pick.tags.clear
    phashtags = self.p_hashtag.scan(/[#＃][a-z|A-Z|가-힣|0-9|\w]+/)
    phashtags.uniq.map do |hashtag|
        tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
        pick.tags << tag
    end
  end

  

end

app/controllers/picks_controller.rb
class PicksController < ApplicationController
  before_action :set_pick, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index, :hashtags]

  # GET /picks
  # GET /picks.json
  def index
    @pagy, @picks = pagy(Pick.all.order("created_at DESC"), items: 20)
  end

  # GET /picks/1
  # GET /picks/1.json
  def show
  end

  def hashtags
    tag = Tag.find_by(name: params[:name])
    @pagy, @picks = pagy(tag.picks.order("created_at DESC"), items: 20)
  end

  # GET /picks/new
  def new
    @pick = Pick.new
  end

  # GET /picks/1/edit
  def edit
  end

  # POST /picks
  # POST /picks.json
  def create
    @pick = Pick.new(pick_params)
    @pick.user = current_user
    respond_to do |format|
      if @pick.save
        format.html { redirect_to "/picks", notice: 'Pick was successfully created.' }
        format.json { render :show, status: :created, location: @pick }
      else
        format.html { render :new }
        format.json { render json: @pick.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /picks/1
  # PATCH/PUT /picks/1.json
  def update
    respond_to do |format|
      if @pick.update(pick_params)
        format.html { redirect_to "/picks", notice: 'Pick was successfully updated.' }
        format.json { render :show, status: :ok, location: @pick }
      else
        format.html { render :edit }
        format.json { render json: @pick.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /picks/1
  # DELETE /picks/1.json
  def destroy
    @pick.destroy
    respond_to do |format|
      format.html { redirect_to picks_url, notice: 'Pick was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pick
      @pick = Pick.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pick_params
      params.require(:pick).permit(:p_title, :p_link, :p_source, :p_hashtag, :p_image, :p_description, :p_spare_01, :p_spare_02, :p_spare_03)
    end
end

app/helpers/picks_helper.rb
module PicksHelper
  def render_with_phashtags(p_hashtag)
    p_hashtag.gsub(/[#＃][a-z|A-Z|가-힣|0-9|\w]+/){|word| link_to word, "/picks/phashtag/#{word.delete('#')}"}.html_safe
  end 
end

app/views/picks/_categories.html.erb
<div class="category-pc clearfix cat-common" data-turbolinks="false">
  <nav class="navbar clearfix">
    <ul>
      <li><a href="/picks">Everything</a></li>
      <li><a href="/picks/phashtag/tech">tech</a></li>
      <li><a href="/picks/phashtag/homeware">homeware</a></li>
      <li><a href="/picks/phashtag/kitchen">ktichen</a></li>
      <li><a href="/picks/phashtag/fashion">fashion</a></li>
      <!-- <li><a href="/picks/phashtag/뷰티">뷰티</a></li> -->
      <li><a href="/picks/phashtag/pet_goods">pet_goods</a></li>
      <li><a href="/picks/phashtag/outdoor">outdoor</a></li>
      <li><a href="/picks/phashtag/featured">featured</a></li>
    </ul>
  </nav>
</div>

<div class="category-mobile clearfix cat-common" data-turbolinks="false">
  <nav class="navbar-mobile clearfix">
    <ul class="left picks-left">
      <li><a href="/picks">Everything</a></li>
      <li><a href="/picks/phashtag/tech">tech</a></li>
      <li><a href="/picks/phashtag/homeware">homeware</a></li>
      <li><a href="/picks/phashtag/kitchen">ktichen</a></li>
      <li><a href="/picks/phashtag/fashion">fashion</a></li>
      <li><a href="/picks/phashtag/pet_goods">pet_goods</a></li>
      <!-- <li><a href="/picks/phashtag/뷰티">뷰티</a></li> -->
      <li><a href="/picks/phashtag/outdoor">outdoor</a></li>
      <li><a href="/picks/phashtag/featured">featured</a></li>
    </ul>
    <!-- <ul class="right">
      <li><a href="#n">+ 더보기</a></li>
    </ul> -->
  </nav>
</div>

<script type="text/javascript">
  $(window).scroll(function () {
    console.log($(window).scrollTop())
    if ($(window).scrollTop() > 63) {
      $('.navbar-mobile').addClass('navbar-fixed');
    }
    if ($(window).scrollTop() < 64) {
      $('.navbar-mobile').removeClass('navbar-fixed');
    }
  });
</script>

app/views/picks/_form.html.erb
<div class="hotdeal_form">
  <%= simple_form_for(@pick) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="basic_info">
      <%= f.input :p_image, label: "썸네일" %>
      <%= f.input :p_spare_02, label: "top title" %>
      <%= f.input :p_spare_03, label: "middle title" %>
      <%= f.input :p_title, label: "bottom title" %>
      <%= f.input :p_description, label: "서브 타이틀" %>
      <%= f.input :p_link, label: "Featureds 해시태그 링크" %>
      <%= f.input :p_spare_01, label: "카테고 [tech, homeware, kitchen, fashion, outdoor, featured]" %>
      <%= f.input :p_hashtag, label: "해시태그 [#tech, #homeware, #kitchen, #fashion, #outdoor, #featured], [#시리즈]" %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/picks/_slider.html.erb
<div id="slide_wrapper">
    <p>Color</p>
    <div class="items">
      <a href="#n">
        <div class="img_box">
          <img src="https://images.unsplash.com/photo-1552386763-fecd1454ff43?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MjR8fGF3ZXNvbWV8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60" alt=""/>
        </div>
        <div class="inner"><p>1st depth</p></div>
      </a>
    </div>

    <div class="items">
      <a href="#n">
        <div class="img_box">
          <img src="https://images.unsplash.com/photo-1552386763-fecd1454ff43?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MjR8fGF3ZXNvbWV8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60" alt=""/>
        </div>
        <div class="inner"><p>1st depth</p>  </div>
      </a>
    </div>

    <div class="items">
      <a href="#n">
        <div class="img_box">
          <img src="https://images.unsplash.com/photo-1552386763-fecd1454ff43?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MjR8fGF3ZXNvbWV8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60" alt=""/>
        </div>
        <div class="inner"><p>1st depth</p>  </div>
      </a>
    </div>

    <div class="items">
      <a href="#n">
        <div class="img_box">
          <img src="https://images.unsplash.com/photo-1552386763-fecd1454ff43?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MjR8fGF3ZXNvbWV8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60" alt=""/>
        </div>
        <div class="inner"><p>1st depth</p>  </div>
      </a>
    </div>

    <div class="items">
      <a href="#n">
        <div class="img_box">
          <img src="https://images.unsplash.com/photo-1552386763-fecd1454ff43?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MjR8fGF3ZXNvbWV8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60" alt=""/>
        </div>
        <div class="inner"><p>1st depth</p>  </div>
      </a>
    </div>
</div>

app/views/picks/edit.html.erb
<% if current_user && current_user.admin %>
  <div class="wrap">
    <h1>Editing Pick</h1>
    <%= render 'form', pick: @pick %>
    <%= link_to 'Show', @pick %> |
    <%= link_to 'Back', picks_path %>
  </div>
<% end %>

app/views/picks/hashtags.html.erb
<%= render 'shared/header' %>

<div class="index-wrap">
  <div class="wrap">

    <div class="visual clearfix">
      <p>감성 큐레이터의 지극히 주관적인</p>
      <h2>We've picked for you!!</h2>
      <!-- < render 'picks/categories' > -->
    </div>

    <div class="hashtag-visual">
      <div class="where-hashtag">
        <% if params[:name].present? %>
          <p><span class="hashtag-through">#<%= params[:name] %></span></p>
        <% end %>
      </div>
    </div>

    <% if current_user && current_user.admin %>
      <div class="index-amdin">
        <%= link_to 'New Pick', new_pick_path %>
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
      </div>
    <% end %>

    <div class="blog-container clearfix">
      <% @picks.each do |pick| %>
        <div class="card">
          <div class="card-header">
              <a class="to_tag" href="/featureds/fhashtag/<%= pick.p_link %>"><img src="<%= pick.p_image %>"></a>
          </div>
          <div class="card-body">
            <p class="tag tag-teal"><a href="/picks/phashtag/<%= pick.p_spare_01 %>">#<%= pick.p_spare_01 %></p>
            <% if current_user && current_user.admin %>
              <p class="tag series"><%= render_with_phashtags(pick.p_hashtag) %></p>
            <% end %>
            
            <a class="to_tag" href="/featureds/fhashtag/<%= pick.p_link %>"><h4><%= pick.p_title %></h4></a>
            <!-- <p><%= pick.p_description %></p> -->
            <div class="card-user">
                <img src="<%=asset_path 'ave71.png' %>" alt="Avenue71">
                <div class="user-info">
                    <h5 >Editor</h5>
                    <small >Avenue71</small>
                </div>
                <div class="admin_management">
                  <% if current_user && current_user.admin %>
                    <span>
                        <%= link_to 'Edit', edit_pick_path(pick) %>
                        <%= link_to 'Destroy', pick, method: :delete, data: { confirm: 'Are you sure?' } %>            
                    </span>
                  <% end %>
                </div>
            </div>
          </div>
        </div>
      <% end %>   
    </div>
    <%= raw pagy_nav(@pagy) %>

    <div class="back_btn_mobile">
      <a href="/picks"><img class="back_btn_m" src="<%=asset_path 'back_btn.png' %>" alt="Go bact to home" /></a>
    </div>
    
  </div><!--./wrap-->
</div><!--./index-wrap->

app/views/picks/index.html.erb
<%= render 'shared/header' %>

<div class="index-wrap blog-wrap">
  <div class="wrap">

    <div class="visual clearfix">
      <p>감성 큐레이터의 지극히 주관적인!!</p>
      <h2>Editor's Picks</h2>
      <%= render 'picks/categories' %>
    </div>

    <% if current_user && current_user.admin %>
      <div class="index-amdin">
        <%= link_to 'New Pick', new_pick_path %> |
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete %> |
      </div>
    <% end %>
    
    <div class="blog-container clearfix">

     <!-- <div class="card banner">
        <div class="card-header">
            <a class="to_tag" href="/sales"><img src="https://images.unsplash.com/photo-1607083206869-4c7672e72a8a?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8c2FsZXxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60"></a>
        </div>
        <div class="card-body">
          <a class="to_tag" href="/sales"><p class="banner-title">쿠팡 50% 할인 모음</p></a>
        </div>
      </div> -->


      <!-- < render "picks/slider" > -->



      <% @picks.each do |pick| %>
        <div class="card">
          <div class="card-header">
              <a class="to_tag" href="/featureds/fhashtag/<%= pick.p_link %>"><img src="<%= pick.p_image %>"></a>
          </div>
          <div class="card-body">
            
              <!-- <p class="tag tag-teal"><%= pick.p_spare_01 %></p> -->
              <% if current_user && current_user.admin %>
                <p class="tag series"><%= render_with_phashtags(pick.p_hashtag) %></p>
              <% end %>
                
              <a class="to_tag a_title" href="/featureds/fhashtag/<%= pick.p_link %>"><h4><%= pick.p_title %></h4></a>
              <!-- <a class="to_tag" href="/featureds/fhashtag/<%= pick.p_link %>">+ 더보기</a> -->



             <!-- <div class="title_section">
                <a class="to_tag" href="/featureds/fhashtag/<%= pick.p_link %>"><em class="top_title"><%= pick.p_spare_02 %></em></a>              
                <a class="to_tag" href="/featureds/fhashtag/<%= pick.p_link %>"><em class="middle_title"><%= pick.p_spare_03 %></em></a>              
                <a class="to_tag" href="/featureds/fhashtag/<%= pick.p_link %>"><em class="bottom_title"><%= pick.p_title %></em></a>              
              </div> -->

              <!-- <p><%= pick.p_description %></p> -->
            

            <div class="card-user">
              <img src="<%=asset_path 'ave71.png' %>" alt="Avenue71">
              <div class="user-info">
                  <h5 >Editor</h5>
                  <small >Avenue71</small>
              </div>
              <div class="admin_management">
                <% if current_user && current_user.admin %>
                  <span>
                      <%= link_to 'Edit', edit_pick_path(pick) %>
                      <%= link_to 'Destroy', pick, method: :delete, data: { confirm: 'Are you sure?' } %>            
                  </span>
                <% end %>
              </div>
            </div>

          </div>

        </div>
      <% end %>   
    </div>
    <%= raw pagy_nav(@pagy) %>
    
  </div><!--./wrap-->
</div><!--./index-wrap-->

<%= render 'shared/footer' %>

app/views/picks/new.html.erb
<% if current_user && current_user.admin %>
  <div class="wrap">
    <h1>New Pick</h1>
    <%= render 'form', pick: @pick %>
    <%= link_to 'Back', picks_path %>
  </div>
<% end %>

app/views/picks/show.html.erb
<%= link_to 'Edit', edit_pick_path(@pick) %> |
<%= link_to 'Back', picks_path %>