config/routes.rb
Rails.application.routes.draw do
  
  get 'bridge/index'
  resources :themes
  resources :sitemap, :only => :index
  get 'sitemap.xml', :controller => "sitemap", :action => "xml"

  resources :scategories
  resources :picks
  resources :featureds
  # root 'posts#index'
  root 'picks#index'


  resources :sales
  devise_for :users
  resources :posts

  get '/sales/hashtag/:name', to:'sales#hashtags'
  get '/featureds/fhashtag/:name', to:'featureds#hashtags'
  get '/picks/phashtag/:name', to:'picks#hashtags'


  #Bridge Page
  get '/bridge/manage_hashtags'
  get '/bridge/top_100'
  get '/bridge/half_deal'
  get '/bridge/under_deal'
  get '/bridge/sales'
  get '/bridge/delete_old_deal'
  get '/bridge/search'
  get '/bridge/about_us'
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/scategory.rb
class Scategory < ApplicationRecord
  belongs_to :user
end

app/controllers/scategories_controller.rb
class ScategoriesController < ApplicationController
  before_action :set_scategory, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  # GET /scategories
  # GET /scategories.json
  def index
    @scategories = Scategory.all.order("created_at DESC")
  end

  # GET /scategories/1
  # GET /scategories/1.json
  def show
  end

  # GET /scategories/new
  def new
    @scategory = Scategory.new
  end

  # GET /scategories/1/edit
  def edit
  end

  # POST /scategories
  # POST /scategories.json
  def create
    @scategory = Scategory.new(scategory_params)
    @scategory.user = current_user
    respond_to do |format|
      if @scategory.save
        format.html { redirect_to @scategory, notice: 'Scategory was successfully created.' }
        format.json { render :show, status: :created, location: @scategory }
      else
        format.html { render :new }
        format.json { render json: @scategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scategories/1
  # PATCH/PUT /scategories/1.json
  def update
    respond_to do |format|
      if @scategory.update(scategory_params)
        format.html { redirect_to @scategory, notice: 'Scategory was successfully updated.' }
        format.json { render :show, status: :ok, location: @scategory }
      else
        format.html { render :edit }
        format.json { render json: @scategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scategories/1
  # DELETE /scategories/1.json
  def destroy
    @scategory.destroy
    respond_to do |format|
      format.html { redirect_to scategories_url, notice: 'Scategory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scategory
      @scategory = Scategory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def scategory_params
      params.require(:scategory).permit(:scategory_01, :scategory_02, :scategory_03, :scategory_04, :scategory_05, :scategory_06, :scategory_07, :scategory_08, :scategory_09, :scategory_10,
                                        :scategory_11, :scategory_12, :scategory_13, :scategory_14, :scategory_15, :scategory_16, :scategory_17, :scategory_18, :scategory_19, :scategory_20,
                                        :scategory_21, :scategory_22, :scategory_23, :scategory_24, :scategory_25, :scategory_26, :scategory_27, :scategory_28, :scategory_29, :scategory_30)
    end
end

app/helpers/scategories_helper.rb
module ScategoriesHelper
end

app/views/scategories/_form.html.erb
<%= simple_form_for(@scategory) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :scategory_01 %>
    <%= f.input :scategory_02 %>
    <%= f.input :scategory_03 %>
    <%= f.input :scategory_04 %>
    <%= f.input :scategory_05 %>
    <%= f.input :scategory_06 %>
    <%= f.input :scategory_07 %>
    <%= f.input :scategory_08 %>
    <%= f.input :scategory_09 %>
    <%= f.input :scategory_10 %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/scategories/_list.html.erb
<div class="category-pc clearfix cat-common" data-turbolinks="false">
  <nav class="navbar clearfix">
    <ul>
      <li><a href="/sales">Everything</a></li>
      <% @scategories.each do |scat| %>
        <% if scat.scategory_01.present? %>
          <li><a href="/sales/hashtag/<%= scat.scategory_01 %>"><%= scat.scategory_01 %></a></li>
        <% end %>
        <% if scat.scategory_02.present? %>
          <li><a href="/sales/hashtag/<%= scat.scategory_02 %>"><%= scat.scategory_02 %></a></li>
        <% end %>
        <% if scat.scategory_03.present? %>
          <li><a href="/sales/hashtag/<%= scat.scategory_03 %>"><%= scat.scategory_03 %></a></li>
        <% end %>
        <% if scat.scategory_04.present? %>
          <li><a href="/sales/hashtag/<%= scat.scategory_04 %>"><%= scat.scategory_04 %></a></li>
        <% end %>
        <% if scat.scategory_05.present? %>
          <li><a href="/sales/hashtag/<%= scat.scategory_05 %>"><%= scat.scategory_05 %></a></li>
        <% end %>
        <% if scat.scategory_06.present? %>
          <li><a href="/sales/hashtag/<%= scat.scategory_06 %>"><%= scat.scategory_06 %></a></li>
        <% end %>
        <% if scat.scategory_07.present? %>
          <li><a href="/sales/hashtag/<%= scat.scategory_07 %>"><%= scat.scategory_07 %></a></li>
        <% end %>
      <% end %>
    </ul>
  </nav>
</div>

<div class="category-mobile clearfix cat-common" data-turbolinks="false">
  <nav class="navbar clearfix">
    <ul class="left">
      <li><a href="/sales">Everything</a></li>
      <% @scategories.each do |scat| %>
        <% if scat.scategory_01.present? %>
          <li><a href="/sales/hashtag/<%= scat.scategory_01 %>"><%= scat.scategory_01 %></a></li>
        <% end %>
        <% if scat.scategory_02.present? %>
          <li><a href="/sales/hashtag/<%= scat.scategory_02 %>"><%= scat.scategory_02 %></a></li>
        <% end %>
        <% if scat.scategory_03.present? %>
          <li><a href="/sales/hashtag/<%= scat.scategory_03 %>"><%= scat.scategory_03 %></a></li>
        <% end %>
        <% if scat.scategory_04.present? %>
          <li><a href="/sales/hashtag/<%= scat.scategory_04 %>"><%= scat.scategory_04 %></a></li>
        <% end %>
        <% if scat.scategory_05.present? %>
          <li><a href="/sales/hashtag/<%= scat.scategory_05 %>"><%= scat.scategory_05 %></a></li>
        <% end %>
        <% if scat.scategory_06.present? %>
          <li><a href="/sales/hashtag/<%= scat.scategory_06 %>"><%= scat.scategory_06 %></a></li>
        <% end %>
        <% if scat.scategory_07.present? %>
          <li><a href="/sales/hashtag/<%= scat.scategory_07 %>"><%= scat.scategory_07 %></a></li>
        <% end %>
      <% end %>
    </ul>
    <ul class="right">
      <li><a href="/scategories">+ More</a></li>
    </ul>
  </nav>
</div>

<script type="text/javascript">
  $(window).scroll(function () {
    console.log($(window).scrollTop())
    if ($(window).scrollTop() > 63) {
      $('.navbar').addClass('navbar-fixed');
    }
    if ($(window).scrollTop() < 64) {
      $('.navbar').removeClass('navbar-fixed');
    }
  });
</script>

app/views/scategories/edit.html.erb
<% if current_user && current_user.admin %>
  <div class="wrap">
    <h1>Editing Scategory</h1>
    <%= render 'form', scategory: @scategory %>
    <%= link_to 'Show', @scategory %> |
    <%= link_to 'Back', scategories_path %>
  </div>
<% end %>

app/views/scategories/index.html.erb
<%= render 'shared/header' %>
<div class="cat-wrap clearfix">
    
    <% @scategories.each do |scategory| %>
      <div class="cat-box clearfix" data-turbolinks="false">
        <h1>+ More</h1>
        <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for category..." title="Type in a name">
        <ul id="myUL" >
          <% if scategory.scategory_01.present? %>
            <li><a href="/sales/hashtag/<%= scategory.scategory_01 %>"><%= scategory.scategory_01 %></a></li>
          <% end %>
          <% if scategory.scategory_02.present? %>
            <li><a href="/sales/hashtag/<%= scategory.scategory_02 %>"><%= scategory.scategory_02 %></a></li>
          <% end %>
          <% if scategory.scategory_03.present? %>
            <li><a href="/sales/hashtag/<%= scategory.scategory_03 %>"><%= scategory.scategory_03 %></a></li>
          <% end %>
          <% if scategory.scategory_04.present? %>
            <li><a href="/sales/hashtag/<%= scategory.scategory_04 %>"><%= scategory.scategory_04 %></a></li>
          <% end %>
          <% if scategory.scategory_05.present? %>
            <li><a href="/sales/hashtag/<%= scategory.scategory_05 %>"><%= scategory.scategory_05 %></a></li>
          <% end %>
          <% if scategory.scategory_06.present? %>
            <li><a href="/sales/hashtag/<%= scategory.scategory_06 %>"><%= scategory.scategory_06 %></a></li>
          <% end %>
          <% if scategory.scategory_07.present? %>
            <li><a href="/sales/hashtag/<%= scategory.scategory_07 %>"><%= scategory.scategory_07 %></a></li>
          <% end %>
          <% if scategory.scategory_08.present? %>
            <li><a href="/sales/hashtag/<%= scategory.scategory_08 %>"><%= scategory.scategory_08 %></a></li>
          <% end %>
          <% if scategory.scategory_09.present? %>
            <li><a href="/sales/hashtag/<%= scategory.scategory_09 %>"><%= scategory.scategory_09 %></a></li>
          <% end %>
          <% if scategory.scategory_10.present? %>
            <li><a href="/sales/hashtag/<%= scategory.scategory_10 %>"><%= scategory.scategory_10 %></a></li>
          <% end %>
          <% if scategory.scategory_11.present? %>
            <li><a href="/sales/hashtag/<%= scategory.scategory_11 %>"><%= scategory.scategory_11 %></a></li>
          <% end %>
          <% if scategory.scategory_12.present? %>
            <li><a href="/sales/hashtag/<%= scategory.scategory_12 %>"><%= scategory.scategory_12 %></a></li>
          <% end %>
          <% if scategory.scategory_13.present? %>
            <li><a href="/sales/hashtag/<%= scategory.scategory_13 %>"><%= scategory.scategory_13 %></a></li>
          <% end %>
          <% if scategory.scategory_14.present? %>
            <li><a href="/sales/hashtag/<%= scategory.scategory_14 %>"><%= scategory.scategory_14 %></a></li>
          <% end %>
          <% if scategory.scategory_15.present? %>
            <li><a href="/sales/hashtag/<%= scategory.scategory_15 %>"><%= scategory.scategory_15 %></a></li>
          <% end %>
          <% if scategory.scategory_16.present? %>
            <li><a href="/sales/hashtag/<%= scategory.scategory_16 %>"><%= scategory.scategory_16 %></a></li>
          <% end %>
          <% if scategory.scategory_17.present? %>
            <li><a href="/sales/hashtag/<%= scategory.scategory_17 %>"><%= scategory.scategory_17 %></a></li>
          <% end %>
          <% if scategory.scategory_18.present? %>
            <li><a href="/sales/hashtag/<%= scategory.scategory_18 %>"><%= scategory.scategory_18 %></a></li>
          <% end %>
          <% if scategory.scategory_19.present? %>
            <li><a href="/sales/hashtag/<%= scategory.scategory_19 %>"><%= scategory.scategory_19 %></a></li>
          <% end %>
          <% if scategory.scategory_20.present? %>
            <li><a href="/sales/hashtag/<%= scategory.scategory_20 %>"><%= scategory.scategory_20 %></a></li>
          <% end %>
          <% if scategory.scategory_21.present? %>
            <li><a href="/sales/hashtag/<%= scategory.scategory_21 %>"><%= scategory.scategory_21 %></a></li>
          <% end %>
          <% if scategory.scategory_22.present? %>
            <li><a href="/sales/hashtag/<%= scategory.scategory_22 %>"><%= scategory.scategory_22 %></a></li>
          <% end %>
          <% if scategory.scategory_23.present? %>
            <li><a href="/sales/hashtag/<%= scategory.scategory_23 %>"><%= scategory.scategory_23 %></a></li>
          <% end %>
          <% if scategory.scategory_24.present? %>
            <li><a href="/sales/hashtag/<%= scategory.scategory_24 %>"><%= scategory.scategory_24 %></a></li>
          <% end %>
          <% if scategory.scategory_25.present? %>
            <li><a href="/sales/hashtag/<%= scategory.scategory_25 %>"><%= scategory.scategory_25 %></a></li>
          <% end %>
          <% if scategory.scategory_26.present? %>
            <li><a href="/sales/hashtag/<%= scategory.scategory_26 %>"><%= scategory.scategory_26 %></a></li>
          <% end %>
          <% if scategory.scategory_27.present? %>
            <li><a href="/sales/hashtag/<%= scategory.scategory_27 %>"><%= scategory.scategory_27 %></a></li>
          <% end %>
          <% if scategory.scategory_28.present? %>
            <li><a href="/sales/hashtag/<%= scategory.scategory_28 %>"><%= scategory.scategory_28 %></a></li>
          <% end %>
          <% if scategory.scategory_29.present? %>
            <li><a href="/sales/hashtag/<%= scategory.scategory_29 %>"><%= scategory.scategory_29 %></a></li>
          <% end %>
          <% if scategory.scategory_30.present? %>
            <li><a href="/sales/hashtag/<%= scategory.scategory_30 %>"><%= scategory.scategory_30 %></a></li>
          <% end %>
        </ul>
      </div>

      <% if current_user && current_user.admin %>
        <div class="admin">
          <%= link_to 'New Scategory', new_scategory_path %> |
          <%= link_to 'Show', scategory %>
          <%= link_to 'Edit', edit_scategory_path(scategory) %>
          <%= link_to 'Destroy', scategory, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      <% end %>
    <% end %>
  
</div>

<div class="back_btn_mobile">
  <a href="/"><img class="back_btn_m" src="<%=asset_path 'back_btn.png' %>" alt="Go bact to home" /></a>
</div>



<script type="text/javascript">
  function myFunction() {
      var input, filter, ul, li, a, i, txtValue;
      input = document.getElementById("myInput");
      filter = input.value.toUpperCase();
      ul = document.getElementById("myUL");
      li = ul.getElementsByTagName("li");
      for (i = 0; i < li.length; i++) {
          a = li[i].getElementsByTagName("a")[0];
          txtValue = a.textContent || a.innerText;
          if (txtValue.toUpperCase().indexOf(filter) > -1) {
              li[i].style.display = "";
          } else {
              li[i].style.display = "none";
          }
      }
  }
</script>

app/views/scategories/new.html.erb
<% if current_user && current_user.admin %>
  <div class="wrap">
    <h1>New Scategory</h1>
    <%= render 'form', scategory: @scategory %>
    <%= link_to 'Back', scategories_path %>
  </div>
<% end %>

app/views/scategories/show.html.erb
<p>
  <strong>Cat title:</strong>
  <%= @scategory.scategory_01 %>
</p>

<%= link_to 'Edit', edit_scategory_path(@scategory) %> |
<%= link_to 'Back', scategories_path %>