config/routes.rb
Rails.application.routes.draw do
  
  get 'bridge/index'
  resources :themes
  resources :sitemap, :only => :index
  get 'sitemap.xml', :controller => "sitemap", :action => "xml"

  resources :scategories
  resources :picks
  resources :featureds
  # root 'posts#index'
  root 'picks#index'


  resources :sales
  devise_for :users
  resources :posts

  get '/sales/hashtag/:name', to:'sales#hashtags'
  get '/featureds/fhashtag/:name', to:'featureds#hashtags'
  get '/picks/phashtag/:name', to:'picks#hashtags'


  #Bridge Page
  get '/bridge/manage_hashtags'
  get '/bridge/top_100'
  get '/bridge/half_deal'
  get '/bridge/under_deal'
  get '/bridge/sales'
  get '/bridge/delete_old_deal'
  get '/bridge/search'
  get '/bridge/about_us'
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/sale.rb
class Sale < ApplicationRecord
  is_impressionable

  extend FriendlyId
  friendly_id :s_spare_01, use: :slugged

  has_and_belongs_to_many :tags
  belongs_to :user

  validates :s_is_price, presence: true
  validates :s_was_price, presence: true

  after_create do
    sale = Sale.find_by(id: self.id)
    hashtags = self.s_hashtag.scan(/[#＃][a-z|A-Z|가-힣|0-9|\w]+/)
    hashtags.uniq.map do |hashtag|
        tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
        sale.tags << tag
    end
  end
  
  before_update do
    sale = Sale.find_by(id: self.id)
    sale.tags.clear
    hashtags = self.s_hashtag.scan(/[#＃][a-z|A-Z|가-힣|0-9|\w]+/)
    hashtags.uniq.map do |hashtag|
        tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
        sale.tags << tag
    end
  end
  
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index, :hashtags]
  # GET /sales
  # GET /sales.json
  def index
    @pagy, @sales = pagy(Sale.all.order("created_at DESC"), items: 80)
    @scategories = Scategory.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
    impressionist(@sale)
  end

  def hashtags
    tag = Tag.find_by(name: params[:name])
    @pagy, @sales = pagy(tag.sales.order("created_at DESC"), items: 80)
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)
    @sale.user = current_user
    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to "/bridge/delete_old_deal", notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sale_params
      params.require(:sale).permit(:s_title, :s_link, :user_id, :s_source, :s_hashtag, :s_video, :s_description,
                                   :s_is_price, :s_was_price, :s_pct, :s_image, :s_rocket, :s_spare_01, :s_spare_02, :s_spare_03)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
  def render_with_hashtags(s_hashtag)
    s_hashtag.gsub(/[#＃][a-z|A-Z|가-힣|0-9|\w]+/){|word| link_to word, "/sales/hashtag/#{word.delete('#')}"}.html_safe
  end 
end

app/views/sales/_categories.html.erb
<div class="category-pc clearfix cat-common" data-turbolinks="false">
  <nav class="navbar clearfix">
    <ul>
      <li><a href="/bridge/sales">Everything</a></li>
      <li><a href="/bridge/half_deal">오늘의 반값할인</a></li>
      <li><a href="/bridge/under_deal">오늘의 만원이하</a></li>
      <!-- <li><a href="/themes">핫딜 픽 더보기</a></li> -->
      <!-- <li><a href="/sales/hashtag/homeware">Homeware</a></li>
      <li><a href="/sales/hashtag/kitchen">Kitchen</a></li>
      <li><a href="/sales/hashtag/fashion">Fashion</a></li>
      <li><a href="/sales/hashtag/beauty">Beauty</a></li>
      <li><a href="/sales/hashtag/outdoor">Outdoor</a></li>
      <li><a href="/sales/hashtag/pet_supplies">Pet_Supplies</a></li>
      <li><a href="/themes">Sale Guide</a></li> -->
      <!-- <li><a href="/scategories">+ More</a></li> -->
    </ul>
  </nav>
</div>

<div class="category-mobile clearfix cat-common" data-turbolinks="false">
  <nav class="navbar-mobile clearfix">
    <ul class="left">
      <li><a href="/bridge/sales">Everything</a></li>
      <li><a href="/bridge/half_deal">오늘의 반값할인</a></li>
      <li><a href="/bridge/under_deal">오늘의 만원이하</a></li>
      <!-- <li><a href="/themes">핫딜 픽 더보기</a></li> -->
      <!-- <li><a href="/sales/hashtag/tech">Tech</a></li>
      <li><a href="/sales/hashtag/homeware">Homeware</a></li>
      <li><a href="/sales/hashtag/kitchen">Kitchen</a></li>
      <li><a href="/sales/hashtag/fashion">Fashion</a></li>
      <li><a href="/sales/hashtag/beauty">Beauty</a></li>
      <li><a href="/sales/hashtag/outdoor">Outdoor</a></li>
      <li><a href="/sales/hashtag/pet_supplies">Pet_Supplies</a></li>
      <li><a href="/themes">Sale Guide</a></li> -->
    </ul>
    <!-- <ul class="right">
      <li><a href="/scategories">+ More</a></li>
    </ul> -->
  </nav>
</div>

<script type="text/javascript">
  $(window).scroll(function () {
    console.log($(window).scrollTop())
    if ($(window).scrollTop() > 63) {
      $('.navbar-mobile').addClass('navbar-fixed');
    }
    if ($(window).scrollTop() < 64) {
      $('.navbar-mobile').removeClass('navbar-fixed');
    }
  });
</script>

app/views/sales/_form.html.erb
<div class="hotdeal_form">
  <%= simple_form_for(@sale) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="basic_info">
      <%= f.input :s_title, label: "상품명" %>
      <%= f.input :s_spare_01, label: "상품 영문" %>
      <%= f.input :s_image, label: "상품 이미지" %>
      <%= f.input :s_link, label: "상품 링크" %>
      <!-- <%= f.input :s_source,  label: "판매 사이트" %> -->
      <%= f.input :s_rocket, label: "로켓배송" %>
      <%= f.input :s_hashtag, label: "해시태그[#tech, #homeware, #kitchen, #fashion, #beauty, #outdoor, #pet, #만원이하, #반값이상할인]" %>
      
    </div>
    <div class="pricing clearfix">
      <%= f.input :s_is_price, label: "현재가격" %>
      <%= f.input :s_was_price, label: "세일전 가격" %>
      <%= f.input :s_spare_02, label: "평점" %>
      <%= f.input :s_spare_03, label: "리뷰수" %>
      <%= f.input :s_pct, label: "할인율" %>

      <!-- <%= f.association :user %> -->
      <!-- <%= f.input :s_video %> -->
      <!-- <%= f.input :s_description %> -->
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>



  

app/views/sales/_menu.html.erb
<!-- <header>
  <div class="wr_Content flex"><a id="logo" href="/">LOGO</a>
    <nav class="flex"><a href="">button_1</a><a href="">button_2</a><a href="">button_3</a>
    </nav>
    <div id="search">
      <input type="text" placeholder="Поиск по сайту"/>
    </div>
  </div>
</header> -->

<nav class="sticky-menu" id="menu">
  <ul class="left">
    <li class="item"><a href="/sales">Everything</a></li>
    <li class="item"><a href="/sales/hashtag/테스트1">테스트1,</a></li>
    <li class="item"><a href="/sales/hashtag/테스트2">테스트2,</a></li>
    <li class="item"><a href="/sales/hashtag/electronics">Electronics,</a></li>
    <li class="item"><a href="/sales/hashtag/home">Home,</a></li>
    <li class="item"><a href="/sales/hashtag/kitchen">Kitchen,</a></li>
    <li class="item"><a href="/sales/hashtag/fashion">Fashion,</a></li>
    <li class="item"><a href="/sales/hashtag/outdoor">Outdoor,</a></li>
    <li class="item"><a href="/sales/hashtag/pet_supplies">Pet Supplies</a></li>
  </ul>
  <ul class="right">
    <li class="item"><a href="#n">+ More</a></li>
  </ul>
</nav>



      

<script type="text/javascript">
  function sticky() {
  var nav = document.querySelector("#menu"),
      H = nav.offsetHeight,
      nav_prev = document.querySelector("header");

  function stickyOn(){
    nav.classList.add("sticky");
    nav_prev.style.marginBottom = H + 'px';
  }
  function stickyOff() {
    nav.classList.remove("sticky");
    nav_prev.style.marginBottom = '';
  }

  ( window.scrollY > H ) ? stickyOn() : stickyOff();

  }
  document.addEventListener("scroll", sticky);
</script>

app/views/sales/_sub_cat.html.erb
<div class="index-amdin" data-turbolinks="false">
  <%= link_to 'New Sale', new_sale_path %>
  <a href="/featureds">Featured</a>
  <a href="/bridge/manage_hashtags">Manage Hashtags</a>
  <a href="/bridge/delete_old_deal">Delete Old Deals</a>
  <a href="/scategories">SaleCategory</a>
  <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
</div>

app/views/sales/edit.html.erb
<% if current_user && current_user.admin %>
  <div class="wrap">
    <h1>Editing Sale</h1>
    <%= render 'form', sale: @sale %>
    <%= link_to 'Show', @sale %> |
    <%= link_to 'Back', sales_path %>
  </div>
<% end %>

app/views/sales/hashtags.html.erb
<!-- <div class="topoftop"></div> -->
<%= render 'shared/header' %>
<div class="index-wrap">
  <div class="wrap">

    <div class="hashtag-visual">
      <div class="where-hashtag">
        <% if params[:name].present? %>
          <p><span class="hashtag-through">#<%= params[:name] %></span></p>
        <% end %>
      </div>
    </div>

    <div class="product-border clearfix">
      <% @sales.each do |sale| %>
        <div class="card">
          <div class="image-box">
            <%= link_to image_tag(sale.s_image, alt: sale.s_title, title: sale.s_title), sale %>
          </div>
          <div class="inner">
            <p class="line-break-01" data-turbolinks="false"><%= link_to sale.s_title, sale%></p>
              <span class="list_price"><%= number_to_currency(sale.s_was_price, locale: :kr) %>원</span>
              <span class="current_price"><%= number_to_currency(sale.s_is_price, locale: :kr) %>원</span>
          </div>
            <% hotdeal_pct = 0 %>
            <% hotdeal_pct =  (sale.s_was_price - sale.s_is_price) / sale.s_was_price * 100 %>
            <div class="pct"><p><%= number_to_percentage(hotdeal_pct, precision: 0) %> off</p></div>
        </div>
      <% end %>
    </div>
    <%= raw pagy_nav(@pagy) %>

    <div class="back_btn_mobile">
      <button onclick="goBack()"><img class="go_back" src="<%=asset_path 'back_btn.png' %>" alt="뒤로가기" /></button>
      <script>
        function goBack() {
          window.history.back();
        }
      </script>
    </div>
    
  </div><!--./wrap-->
</div><!--./index-wrap->

app/views/sales/index.html.erb
<%= render 'shared/header' %>
<div class="index-wrap">
  <div class="wrap">

    <div class="visual clearfix">
      <p>너무나 듣고 싶은 한마디</p>
      <h2>사랑해 보다 오늘 세일해</h2>
      <%= render 'sales/categories' %>
    </div>

    <% if current_user && current_user.admin %>
      <%= render 'sales/sub_cat' %>
    <% end %>
    
    <div class="product-border clearfix">
      <% @sales.each do |sale| %>
        <div class="card">
          <div class="image-box">
            <!-- <a href="/sales/<%= sale.id %>" data-turbolinks="false"><img src="<%= sale.s_image %>" alt="<%= sale.s_title %>" title="<%= sale.s_title %>"></a> -->
            <%= link_to image_tag(sale.s_image, alt: sale.s_title, title: sale.s_title), sale %>
            <% if current_user && current_user.admin %>
              <span class="updated_time"><%= time_ago_in_words(sale.created_at) %> ago</span>
              <span class="views_count">views: <%= sale.impressionist_count %></span>
            <% end %>
          </div>
          <div class="inner">
            <p class="line-break-01" data-turbolinks="false"><%= link_to sale.s_title, sale%></p>
            <span class="sale_current_price"><%= number_to_currency(sale.s_is_price, locale: :kr) %>원</span>
            <span class="list_price"><%= number_to_currency(sale.s_was_price, locale: :kr) %>원</span>
            
          </div>
          <% hotdeal_pct = 0 %>
          <% hotdeal_pct =  (sale.s_was_price - sale.s_is_price) / sale.s_was_price * 100 %>
          <div class="pct"><p><%= number_to_percentage(hotdeal_pct, precision: 0) %> off</p></div>
        </div>

      <% end %>
    </div>
    <%= raw pagy_nav(@pagy) %>
    
  </div><!--./wrap-->
</div><!--./index-wrap-->

app/views/sales/new.html.erb
<% if current_user && current_user.admin %>
  <div class="wrap">
    <h1>New Sale</h1>
    <%= render 'form', sale: @sale %>
    <%= link_to 'Back', sales_path %>
  </div>
<% else %>
<% end %>

app/views/sales/show.html.erb
<div class="show-wrap">
  <div class="wrap">

    <div class="container clearfix">

      <!-- <a href="/sales"><img class="go_back" src="<%=asset_path 'go_back.png' %>" alt="Go bact to home" /></a> -->
      <div class="image-box clearfix">
        <img src="<%= @sale.s_image %>" alt="<%= @sale.s_title %>" title="<%= @sale.s_title %>" />
      </div>

      <div class="title">
        <!-- <h2 class="line-break-02"><%= @sale.s_title %></h2> -->
        <h2><%= @sale.s_title %></h2>
        <% if @sale.s_spare_02.present? %>
          <span>평점: <%= @sale.s_spare_02 %> / 리뷰 수: <%= @sale.s_spare_03 %> +</span>
        <% end %>
      </div>

      <div class="inner">
        <h2 class="summary_title">SUMMARY</h2>
        <div class="receipt">
          <!-- Button Section - Text(left) -->
          <div class="receipt__grid1">
            <p>상품 가격</p>
            <% hotdeal_pct = 0 %>
            <% hotdeal_pct =  (@sale.s_was_price.to_i - @sale.s_is_price.to_i) / @sale.s_was_price * 100 %>
            <p class="pct"><%= number_to_percentage(hotdeal_pct, precision: 0) %>세일</p>
            <% if @sale.s_source.present? %>
            <% else %>
              <p>로켓&무료 배송</p>
            <% end %>
          
            <hr>

            <p class="total_text">Total</p>
          </div>

          <!-- Summary Section - Price(right) -->
          <div class="receipt__grid2">
            <p><em>-</em> <%= number_to_currency(@sale.s_was_price, locale: :kr) %>원</p>
            <% discount_price = 0 %>
            <% discount_price = @sale.s_was_price.to_f - @sale.s_is_price.to_f %>
            <p>- <%= number_to_currency(discount_price, locale: :kr) %>원</p>
            <% if @sale.s_source.present? %>
            <% else %>
              <% if @sale.s_rocket.present? %>
                <p>YES</p>
              <% else %>
                <p>NO</p>
              <% end %>
            <% end %>
            <hr>

            <p class="total_price "><%= number_to_currency(@sale.s_is_price, locale: :kr) %>원</p>

          </div>
        </div>
      

        <!-- Button Section -->
        <div class="btn-box clearfix">
          <a class="btn" target="_blank" href="<%= @sale.s_link %>">이거 쿠팡에서 <%= number_to_currency(discount_price, locale: :kr) %>원 할인받기</a>
          <% if current_user && current_user.admin %>
            <div class="admin">
              <p class="hashtag"><%= render_with_hashtags(@sale.s_hashtag) %></p>
              <%= link_to 'Back', sales_path %> | 
              <%= link_to 'Edit', edit_sale_path(@sale) %> |
              <%= link_to 'Destroy', @sale, method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
          <% end %>
        </div>

        <div class="notice clearfix">
          <span>상품 가격과 세일 정보는 포스팅 이후 변경 될 수 있어요.</span>
          <span>파트너스 활동을 통해 일정의 수수료를 지급받아요.</span>
          <!-- <span></span> -->
        </div>

      </div><!--./inner->
    
    </div><!--./container-->

    <div class="two-btn">
      <a href="/sales"><img src="<%=asset_path 'go_back.png' %>">home</a>
      <a href="/themes">Sale Guide<img class="go_sale_guide" src="<%=asset_path 'go_back.png' %>"></a>
    </div>


  </div>
</div>